spring:
  application:
    name: RegBoard

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

  mvc:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    root: INFO
    org.springframework: INFO
    ru.itis: DEBUG
  file:
    name: logs/app.log

jwt:
  secret-key: ${JWT_SECRET}
  expiration: 3_600_000

minio:
  url: http://${MINIO_HOST:minio}:${MINIO_PORT:9000}
  bucket: events-images
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}

api:
  qr:
    url: https://api.qrserver.com/v1/create-qr-code/
    size: 200x200

server-address: http://localhost:8080